# Generated by Django 5.0.4 on 2024-06-27 23:11

import app1.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.CharField(default=app1.models.generate_id, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
            options={
                'default_related_name': 'assign_users',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None)),
                ('description', models.TextField()),
                ('raised_by', models.CharField(max_length=100)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_time', models.CharField(choices=[('Normal', 'Normal (10-15 days)'), ('Immediate', 'Immediate (3-4 days)')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Allotted', 'Allotted'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='complaint_images/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.assign')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
        migrations.AddField(
            model_name='assign',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department'),
        ),
    ]
