# Generated by Django 5.0.6 on 2024-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_assign_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$jTbLI1CO5PAmUHBAIlvEjF$AhLc2NVlsupckXxu89WGBb1YC/DI0dxcgybPjEt8BLc=', max_length=128),
        ),
    ]
