# Generated by Django 5.0.6 on 2024-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_complaint_date_alloted_complaint_date_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$lHkG178UyaKAb9teVwMBrR$OBA7vQd9Rk2LCFePZcp2/e+rPyYsS7ZRmoelalavyew=', max_length=128),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.FileField(default='exit', upload_to='complaint_images/'),
            preserve_default=False,
        ),
    ]
