# Generated by Django 5.0.6 on 2024-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_assign_password_alter_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$lFNRxmjqsKtcwj5bsUR9ZQ$aQVxJB5fmXE986gcGUWGkGcsA8OUAj0hu3uptBzkGIc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.FileField(default=FileNotFoundError, upload_to='complaint_images/'),
        ),
    ]
