# Generated by Django 5.0.6 on 2024-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_assign_password_alter_complaint_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$VzJsbbuSinVeEZeqaMNwSY$olFOamWSdnkSNCIlHdTz4n9YdRExBnLyOMN9NAol5KY=', max_length=128),
        ),
    ]
