# Generated by Django 5.0.6 on 2024-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_assign_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$J5ysY1lqbIQzw9kAie37Kw$lrSCii8IqyXAfW/pz4n/O3JEHgGzy0R43mn3hNX0AlI=', max_length=128),
        ),
    ]
