# Generated by Django 5.0.6 on 2024-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_assign_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='password',
            field=models.CharField(default='Pass123', max_length=128),
        ),
    ]
