# Generated by Django 5.0.6 on 2024-07-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_assign_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='password',
        ),
    ]
